Repository AICoE/elyra-aidevsecops-tutorial, pull requests merged in 2021-02, with the labels that each got.

#51 Fix broken link.
  README.md
Labels: approved, size/XS

#54 Update download dataset notebook
  notebooks/download_dataset.ipynb
Labels: approved, size/L

#57 Include option to use Ceph for Kubeflow Pipeline on Tekton
  Pipfile
  Pipfile.lock
  elyra-aidevsecops-tutorial.pipeline
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
Labels: approved, size/XXL

#61 Add notebook to test deployed model
  notebooks/test_deployed_model.ipynb
Labels: approved, size/L

#46 Improve doc tutorial
  README.md
  docs/images/AIPipeline.png
  docs/images/AIPipelineStepInputs.png
  docs/images/AIProjectTemplate.png
  docs/images/AddRuntimeImage.png
  docs/images/CloneYourRepo.png
  docs/images/CreateNewElyraRuntime.png
  docs/images/ElyraGitExtension.png
  docs/images/ElyraRuntimeButton.png
  docs/images/ElyraRuntimeTab.png
  docs/images/FillInputsRuntimeImage.png
  docs/images/ImageRegistry.png
  docs/images/JupyterHubUI.png
  docs/images/ManageRuntimeImageSettings.png
  docs/images/OpenIssueRelease.png
  docs/images/PullRequestRelease.png
  docs/images/UpdatedRuntimeImageList.png
Labels: approved, size/L

#62 Correct name images
  docs/images/ElyraRuntimeButton.png
  docs/images/ElyraRuntimeTab.png
  docs/images/InsertInputsElyraRuntime.png
Labels: approved, size/XS

#64 Add image and step on how to start new pipeline editor in Elyra
  README.md
  docs/images/NewElyraPipelineEditor.png
Labels: approved, size/S

#65 Add screenshots on how to run the Elyra AI Pipeline
  README.md
  docs/images/AIPipelineRunInputs.png
  docs/images/InsertInputsElyraRuntime.png
  docs/images/PlayAIPipeline.png
Labels: approved, size/S

#66 Correct sentence
  README.md
Labels: approved, size/XS

#67 Correct notebook link and add one image in docs
  README.md
  docs/images/KFPUI.png
Labels: approved, size/XS

#68 Add notebook dependencies in notebooks and overlays matchin notebook kernels and dependencies using jupyterlab-requirements
  .thoth.yaml
  Pipfile
  Pipfile.lock
  notebooks/download_dataset.ipynb
  notebooks/test_deployed_model.ipynb
  notebooks/training.ipynb
  overlays/download_dataset/Pipfile
  overlays/download_dataset/Pipfile.lock
  overlays/test_model/Pipfile
  overlays/test_model/Pipfile.lock
  overlays/training/Pipfile
  overlays/training/Pipfile.lock
Labels: approved, size/XXL

#69 adjust-overlays
  .thoth.yaml
  overlays/inference/Pipfile
  overlays/inference/Pipfile.lock
Labels: approved, size/L

#71 Restore overlay for training
  README.md
  overlays/training/Pipfile
  overlays/training/Pipfile.lock
Labels: approved, size/XL

#70 update ci config to support build and delivery from overlay
  .aicoe-ci.yaml
  .thoth.yaml
  overlays/download-dataset/Pipfile
  overlays/download-dataset/Pipfile.lock
  overlays/test-model/Pipfile
  overlays/test-model/Pipfile.lock
Labels: approved, sig/docs, size/M

#74 Update notebook metadata for download-dataset
  Pipfile
  Pipfile.lock
  notebooks/download_dataset.ipynb
  overlays/download-dataset/Pipfile.lock
Labels: approved, size/L

#75 Updated steps in the tutorial
  README.md
Labels: approved, size/L

#76 Adjust image links
  README.md
Labels: approved, lgtm, size/XS

#77 Add link to AICOE yaml for clarification
  README.md
Labels: approved, size/XS

#78 Add latency to output of predicted model
  README.md
  src/test.py
  wsgi.py
Labels: approved, size/S

#79 Optional loading of the model from Ceph
  notebooks/download_dataset.ipynb
  notebooks/test_deployed_model.ipynb
  notebooks/training.ipynb
  src/model.py
Labels: approved, size/M

#82 Add missing package to overlay
  overlays/download-dataset/Pipfile
  overlays/download-dataset/Pipfile.lock
Labels: approved, size/L

#83 adjust-notebook
  notebooks/download_dataset.ipynb
Labels: approved, size/S

#84 Connect once to S3
  notebooks/download_dataset.ipynb
Labels: approved, size/M

#85 Add completed pipeline
  README.md
  docs/images/SuccessfullKubeflowPipeline.png
Labels: approved, size/M

#86 Add store model ceph
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
Labels: approved, size/L

#87 Adjust test script and test notebook
  notebooks/download_dataset.ipynb
  notebooks/test_deployed_model.ipynb
  notebooks/training.ipynb
  src/test.py
Labels: approved, size/M

#88 Update description of successfull pipeline
  README.md
Labels: approved, size/XS

#91 Update notebook dependencies
  notebooks/download_dataset.ipynb
Labels: approved, size/S

#92 Update image for runtime images creation using command palette
  README.md
  docs/images/ManageRuntimeImageSettings.png
  docs/images/ManageRuntimeImageSettingsCM.png
Labels: approved, size/XS

#93 Add description on how to Push changes to GitHub
  README.md
  docs/images/PushGitHubToken.png
  docs/images/UseButtonToPushChanges.png
Labels: approved, size/S

#95 Adjust software stack not to use *
  Pipfile
  Pipfile.lock
  notebooks/download_dataset.ipynb
  overlays/download-dataset/Pipfile
  overlays/download-dataset/Pipfile.lock
Labels: approved, size/L

#94 Add links to KFP and Tekton
  README.md
Labels: approved, size/XS

#96 Change section order
  README.md
Labels: approved, size/S

#98 Add ArgoCD image and description
  README.md
  docs/images/ArgoCDUI.png
Labels: approved, size/S

#99 Add Kebechet update image
  README.md
  docs/images/KebechetAutomaticUpdate.png
Labels: approved, size/XS

#100 Improve Runtime images part
  README.md
Labels: approved, size/S

#101 Add inputs for Kubeflow Pipeline inputs
  README.md
Labels: approved, size/S

#102 Adjust step
  README.md
  notebooks/test_deployed_model.ipynb
Labels: approved, size/XS

#103 Add URL GitHub repo to be cloned
  README.md
Labels: approved, size/XS

#104 Describe where to find information for the bucket
  README.md
Labels: approved, size/S

#105 Describe Git Extenstion use
  README.md
  docs/images/TakeLinkForkedRepo.png
Labels: approved, size/S

#106 Final changes
  elyra-aidevsecops-tutorial-2.pipeline
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
Labels: approved, size/L

#107 Add Openshift example
  README.md
Labels: approved, size/S

#108 Add links manifest
  README.md
Labels: approved, size/XS

#109 Configure overlays directory
  .thoth.yaml
Labels: approved, lgtm, size/XS

#111 Refactor and correct errors
  README.md
  docs/source/build-images.md
  docs/source/create-ai-pipeline.md
  docs/source/deploy-model.md
  docs/source/explore-notebooks-and-manage-dependencies.md
  docs/source/monitor-model.md
  docs/source/pre-requisite.md
  docs/source/push-changes.md
  docs/source/run-ai-pipeline.md
  docs/source/setup-initial-environment.md
  docs/source/test-model.md
  docs/source/use-bots.md
  elyra-aidevsecops-tutorial-2.pipeline
  manifests/base/deploymentconfig.yaml
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
Labels: approved, size/XL

#112 Update reference
  README.md
Labels: approved, size/XS

#113 Add missing references
  README.md
  docs/source/setup-initial-environment.md
Labels: approved, size/S

#114 Correct requirements
  README.md
  docs/source/deploy-model.md
Labels: approved, size/XS
