Repository AICoE/elyra-aidevsecops-tutorial, pull requests merged in 2021-04, with the labels that each got.

#134 Adjust KFP UI URL
  docs/source/run-ai-pipeline.md
Labels: approved, lgtm, size/XS

#128 Add correct KFP URL to run pipeline
  docs/source/create-ai-pipeline.md
Labels: approved, lgtm, size/XS

#135 Fix pipeline GitHub URL
  docs/source/create-ai-pipeline.md
Labels: approved, lgtm, ok-to-test, size/XS

#138 Make tutorial an exeriment to be spawned by JH on Operate First
  .aicoe-ci.yaml
  .thoth.yaml
  overlays/experiment/Pipfile
  overlays/experiment/Pipfile.lock
Labels: approved, size/S

#145 Add test
  overlays/test-model/Pipfile
  overlays/test-model/Pipfile.lock
  src/test.py
Labels: approved, size/XL
