Repository AICoE/elyra-aidevsecops-tutorial, pull requests merged in 2021-08, with the labels that each got.

#214 fixing broken links
  docs/source/build-images.md
  docs/source/create-ai-pipeline.md
  docs/source/monitor-model.md
  docs/source/push-changes.md
  docs/source/setup-initial-environment.md
Labels: approved, lgtm, size/S

#221 modified push changes doc
  docs/source/push-changes.md
Labels: approved, size/XS, lgtm

#233 add prose to set up aicoe-ci
  docs/images/EnableForkIssues.png
  docs/images/InviteSesheta.png
  docs/source/build-images.md
Labels: approved, size/M, lgtm

#243 new base custom image
  .aicoe-ci.yaml
Labels: size/XS

#237 added more instructions to create pipeline
  docs/images/AddComments.png
  docs/images/DownloadDatasetProperties.png
  docs/images/NotebookProperties.png
  docs/images/TrainingProperties.png
  docs/source/create-ai-pipeline.md
Labels: approved, size/M, lgtm

#235 add instructions for kebechet
  docs/source/use-bots.md
Labels: approved, size/M, lgtm

#251 fix links in pre-requisite.md
  docs/source/pre-requisite.md
Labels: approved, size/XS, lgtm

#247 add conclusion docs
  docs/source/conclusion.md
  docs/source/monitor-model.md
Labels: approved, size/S

#250 added documentation for using secrets
  docs/images/DownloadDatasetProperties.png
  docs/images/TrainingProperties.png
  docs/source/create-ai-pipeline.md
  elyra-aidevsecops-tutorial.pipeline
Labels: approved, size/M, lgtm

#252 define prereqs with meteor
  docs/source/pre-requisite.md
Labels: approved, size/XS

#254 update flask-app prose
  docs/source/model-deployment/flask-application.md
Labels: approved, size/S

#255 "Contact us" prose in `build-images.md`
  docs/source/build-images.md
Labels: approved, size/XS

#258 Use thoth-advise manager
  .thoth.yaml
Labels: approved, size/XS

#267 Update manage dependencies section
  docs/images/JupyterLabHorusCheck.png
  docs/images/JupyterLabHorusShow.png
  docs/images/JupyterLabRequirementsExtensionCLI.png
  docs/images/JupyterLabRequirementsExtensionMC.png
  docs/source/explore-notebooks-and-manage-dependencies.md
Labels: approved, size/M

#273 Update push changes
  docs/images/CommitChanges.png
  docs/images/FirsCommit.png
  docs/images/GotoGitBoxPanel.png
  docs/images/OpenTerminal.png
  docs/images/StageFiles.png
  docs/images/UseTerminal.png
  docs/source/push-changes.md
  docs/source/setup-initial-environment.md
Labels: size/M

#274 Update bots and release section
  docs/images/KhebutAutomaticUpdate.png
  docs/source/build-images.md
  docs/source/use-bots.md
Labels: size/L

#281 Merge content for book
  _toc.yml
Labels: approved

#257 update TOC
  _toc.yml
Labels: size/XS
