Repository AICoE/elyra-aidevsecops-tutorial, pull requests merged in 2021-07, with the labels that each got.

#167 Updated Training Notebook
  notebooks/training.ipynb
Labels: approved, size/M

#181 Add library for experiment overlay
  overlays/experiment/Pipfile
  overlays/experiment/Pipfile.lock
Labels: size/XXL

#187 Modify approvers and reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#186 add relative links in md
  README.md
  docs/source/build-images.md
  docs/source/create-ai-pipeline.md
  docs/source/deploy-model.md
  docs/source/explore-notebooks-and-manage-dependencies.md
  docs/source/model-deployment/flask-application.md
  docs/source/setup-initial-environment.md
  docs/source/test-model.md
Labels: approved, size/M

#191 Use new elyra custom image for build
  .aicoe-ci.yaml
Labels: lgtm

#202 Proofread and edit `run-ai-pipeline.md`
  docs/source/run-ai-pipeline.md
Labels: approved, lgtm, size/S

#200 Proofread and edit test-model.md
  docs/source/test-model.md
Labels: approved, lgtm, size/S

#205 update pre-req.md
  docs/source/pre-requisite.md
Labels: approved, size/M

#206 update `explore nb` markdown
  docs/images/JupyterLabRequirementsExtension.jpg
  docs/source/explore-notebooks-and-manage-dependencies.md
Labels: approved, size/S

#201 Proofread and update `setup-initial-environment.md`
  docs/images/JupyterHubNewUI.png
  docs/source/setup-initial-environment.md
Labels: approved, lgtm, size/M

#208 Update model deployment docs
  docs/source/deploy-model.md
  docs/source/model-deployment/flask-application.md
Labels: approved, lgtm, size/M

#197 modifying notebooks for automation
  elyra-aidevsecops-tutorial.pipeline
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
Labels: approved, size/L

#207 modified create ai pipeline doc
  docs/images/FillInputsRuntimeImage.png
  docs/images/UpdatedRuntimeImageList.png
  docs/source/create-ai-pipeline.md
Labels: approved, size/M

#203 Update and proofread `README.md`
  README.md
Labels: approved, size/M

#204 Proofread and update `use-bots` documentation
  README.md
  docs/source/use-bots.md
Labels: approved, lgtm, size/S

#209 Proofread and update `build-images` doc
  docs/source/build-images.md
Labels: approved, size/M
