Repository AICoE/elyra-aidevsecops-tutorial, pull requests merged in 2021-05, with the labels that each got.

#146 Download and test script
  overlays/test-model/Pipfile
  overlays/test-model/Pipfile.lock
  src/test.py
Labels: approved, size/L

#148 Use behave for gathering metrics and running integration test
  .pre-commit-config.yaml
  .prow.yaml
  .thoth.yaml
  Makefile
  docs/Makefile
  docs/commands.rst
  docs/conf.py
  docs/getting-started.rst
  docs/index.rst
  docs/make.bat
  features/gather_deployment_metrics.feature
  features/steps/model_deployment.py
  overlays/test-model/Pipfile
  overlays/test-model/Pipfile.lock
  src/features/.gitkeep
  src/features/__init__.py
  src/features/build_features.py
  tox.ini
Labels: approved, size/XL

#151 Update the aicoe-ci config file with proper image
  .aicoe-ci.yaml
Labels: approved, size/XS

#152 Add variable to store metrics
  features/steps/model_deployment.py
Labels: approved, size/S

#153 Add missing references
  README.md
Labels: approved, size/XS

#154 Describe Integration test
  docs/ML-Prague-2021-Workshop.pdf
  docs/source/test-model.md
  features/steps/model_deployment.py
Labels: approved, size/M

#159 update the prow resource limits
  .prow.yaml
Labels: approved, size/S

#157 add more metrics
  features/steps/model_deployment.py
Labels: approved, size/S

#163 Update .aicoe-ci.yaml
  .aicoe-ci.yaml
Labels: approved, size/XS
