Repository AICoE/elyra-aidevsecops-tutorial, pull requests merged in 2021-01, with the labels that each got.

#5 Adjust notebook and pipeline version
  notebooks/download_dataset.ipynb
  tutorial.pipeline
Labels: approved, size/L

#6 add packages
  Pipfile
  Pipfile.lock
Labels: approved, size/XXL

#7 Add training notebook
  Pipfile.lock
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
Labels: approved, size/XL

#9 Update pipeline
  tutorial.pipeline
Labels: approved, size/M

#11 Add new dependencies
  Pipfile
  Pipfile.lock
  README.md
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
  src/common.py
  tutorial.pipeline
Labels: approved, size/XL

#13 Update thoth yaml
  .thoth.yaml
Labels: approved, kind/feature, sig/user-experience, size/S

#16 Update aicoe yaml
  .aicoe-ci.yaml
Labels: approved, sig/devops, size/S

#15 Add manifests
  manifests/.sops.yaml
  manifests/README.md
  manifests/base/deploymentconfig.yaml
  manifests/base/imagestreamtag.yaml
  manifests/base/kustomization.yaml
  manifests/base/route.yaml
  manifests/base/service.yaml
  manifests/cronwf.yaml
  manifests/imagestream.yaml
  manifests/ksops.yaml
  manifests/kustomization.yaml
  manifests/postsync-wf.yaml
  manifests/wftmpl.yaml
Labels: approved, do-not-merge/hold, size/L

#18 Add overlays
  manifests/base/deploymentconfig.yaml
  manifests/base/imagestream.yaml
  manifests/base/kustomization.yaml
  manifests/base/route.yaml
  manifests/base/service.yaml
  manifests/overlays/test/imagestreamtag.yaml
  manifests/overlays/test/kustomization.yaml
Labels: approved, size/M

#12 Create flask app with endpoints to request prediction and metrics
  README.md
  src/model.py
  src/test.py
  wsgi.py
Labels: approved, kind/feature, sig/devops, sig/documentation, sig/user-experience, size/L

#21 Adjust pre-commit
  notebooks/download_dataset.ipynb
  notebooks/training.ipynb
  src/model.py
  src/test.py
  wsgi.py
Labels: approved, size/L

#19 Fix context path overalys for deployment
  .aicoe-ci.yaml
Labels: approved, size/XS

#22 Remove jupyter from dev package
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#27 Add bot approvers for release
  OWNERS
Labels: approved, sig/devops, size/XS

#32 Add gunicorn
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#29 Adjust deploy in .aicoe.yaml for handling correctly the overlays context path
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  manifests/overlays/test/imagestreamtag.yaml
Labels: approved, size/S

#31 Add flask exporter prometheus
  Pipfile
  Pipfile.lock
  wsgi.py
Labels: approved, size/M

#33 Use smart changelog
  .thoth.yaml
Labels: approved, size/XS

#37 Add WIP in README
  README.md
  manifests/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS

#39 Adjust context path for image tag update
  .aicoe-ci.yaml
Labels: approved, size/XS

#40 lets redirect to the readme ;)
  wsgi.py
Labels: approved, size/XS

#42 Update wsgi.py
  wsgi.py
Labels: approved, size/XS

#50 Deploy the Tag v0.2.2 for elyra-aidevsecops-tutorial
  manifests/overlays/test/imagestreamtag.yaml
Labels: approved, size/XS
